### PR TITLE
Changed the git user to dokku and fixed old things

### PR DESCRIPTION
**Pull request by onnimonni**
Used $DOKKU_ROOT and $DOKKU_VOLUME_PATH instead of fixed literals. This is much more maintainable.
TODO:check bugs and to be able to link same mysql-container to multiple apps

### CODE REVIEW

**Comment by 2m** [comment]
I also get the same error:

```
root@dokku:/var/lib/dokku/plugins# dokku mysql:create wordpress
mv: accessing '/var/lib/docker/vfs/dir/mysql-wordpress': Permission denied
```

```
root@dokku:/var/lib/dokku/plugins# dokku version
dev-77-gc5b7a63
root@dokku:/var/lib/dokku/plugins# docker -v
Docker version 0.7.6, build bc3b2ec
```

**Comment by lovek323** [comment]
I am getting the same error: dokku v0.2.1, docker 0.8.0

**Comment by javdl** [comment]
Same here...
<code>
sudo dokku mysql:create dj
/var/lib/dokku/plugins/mysql/commands: line 46: /home/git/.mysql/pwd_dj: Permission denied
</code>

(after creating /home/git and /home/git/.mysql folders manually. At first it was giving this error on /home/git Some permissions/group problem maybe?)

**Comment by onnimonni** [comment]
Sorry for a such delay! There's a lot To fix in this and I found Much better mariadb plugin (which is basically what You too want to use)
Look here: https://github.com/Kloadut/dokku-md-plugin

**Comment by javdl** [comment]
So instead of mysql plugin I should use the MariaDB plugin? thx

**Comment by onnimonni** [comment]
Yeah Kloadut made so fine job there so I didn't bother fixing this. Sorry that I didn't say anything

**Pull request closed without merging**
